### ISSUE TITLE
Fixed Room makes PropagationCost = 1

### ISSUE THREAD

**Issue by ianberman** [VilleOjala/FMOD-Unity-Tools#6]
Hi! 

I think I ran into a bug: if `Fixed Room` is checked in the script Audio Object, the `PropagationCost` will be 1, even if the listener is standing directly outside of an open portal. When I turn `Fixed Room` off, it seems to be calculating `PropagationCost` as expected again.

I noticed a related issue in the ambience system, where `PropagationCost` = 1 for any ambience coming out of a portal -- only if it is assigned a `Spatial Audio Room` in the Ambience Area script. Possibly it's the same thing.

Let me know if I'm misunderstanding something about this or set it up incorrectly - thank you! :)
Ian

**Comment by VilleOjala** [comment]
I took a quick look at this, and it indeed was the case that on update the instances with fixed rooms weren't added to the list of instances with known rooms. Let me know if the simple fix I pushed fixes whole issue for you. 

Ville
